# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='amountQuizMulti',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='amountQuizOne',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='amountQuizShort',
            field=models.IntegerField(null=True),
        ),
    ]
