# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitassign',
            name='submittime',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
