# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_submitassign_submittime'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitassign',
            name='submitTime',
            field=models.DateTimeField(null=True),
        ),
    ]
