# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '__first__'),
        ('student', '0004_submitassign_submittime'),
    ]

    operations = [
        migrations.CreateModel(
            name='quiz_multiManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_multi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz_multi')),
                ('submitAssign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.SubmitAssign')),
            ],
        ),
        migrations.CreateModel(
            name='quiz_oneManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz_one')),
                ('submitAssign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.SubmitAssign')),
            ],
        ),
        migrations.CreateModel(
            name='quiz_shortManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_short', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz_short')),
                ('submitAssign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.SubmitAssign')),
            ],
        ),
        migrations.AddField(
            model_name='submitassign',
            name='quiz_multiIds',
            field=models.ManyToManyField(null=True, through='student.quiz_multiManager', to='quiz.quiz_multi'),
        ),
        migrations.AddField(
            model_name='submitassign',
            name='quiz_oneIds',
            field=models.ManyToManyField(null=True, through='student.quiz_oneManager', to='quiz.quiz_one'),
        ),
        migrations.AddField(
            model_name='submitassign',
            name='quiz_shortIds',
            field=models.ManyToManyField(null=True, through='student.quiz_shortManager', to='quiz.quiz_short'),
        ),
    ]
