# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20170816_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitassign',
            name='quiz_multiIds',
            field=models.ManyToManyField(through='student.quiz_multiManager', to='quiz.quiz_multi'),
        ),
        migrations.AlterField(
            model_name='submitassign',
            name='quiz_oneIds',
            field=models.ManyToManyField(through='student.quiz_oneManager', to='quiz.quiz_one'),
        ),
        migrations.AlterField(
            model_name='submitassign',
            name='quiz_shortIds',
            field=models.ManyToManyField(through='student.quiz_shortManager', to='quiz.quiz_short'),
        ),
    ]
