# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20170816_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz_multimanager',
            old_name='quiz_multi',
            new_name='quiz',
        ),
        migrations.RenameField(
            model_name='quiz_onemanager',
            old_name='quiz_one',
            new_name='quiz',
        ),
        migrations.RenameField(
            model_name='quiz_shortmanager',
            old_name='quiz_short',
            new_name='quiz',
        ),
    ]
